version: '3.5'

services:

  mongoDatabase:
    image: mongo:latest
    container_name: blockchain_db
    restart: always
    ports:
      - "27017:27017"   
    volumes:
      - mongo-data:/data/db
    networks: 
      - backtier
  
  transactions:
    container_name: blockchain_app
    build: .
    command: npm run start:prod
    depends_on: 
      - mongoDatabase
    networks: 
      - backtier
  
volumes:
  mongo-data:
networks: 
  backtier:
    driver: bridge
