version: '3.3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb_blockchain
    restart: always
    ports:
      - "27017:27017"   
    volumes:
      - mongo-data:/data/db
  
  transactions:
    build: .
    depends_on: 
      - mongodb
  
volumes:
  mongo-data:
